### PR TITLE
use dicts for pre-17 Erlang releases

### PR DESCRIPTION
**Pull request by tsloughter**
We wanted to use mustache for rebar3 and relx. See PR's https://github.com/erlware/relx/pull/339 and https://github.com/rebar/rebar3/pull/392

Since these need to support R15 and R16 I had to patch it to use dicts. I've taken those changes and merged them into this branch that uses maps for 17+ and dicts for everything before 17.

I'm fine making some changes to style or trying to have less duplicated code, but what do you think?

### CODE REVIEW

**Comment by soranoba** [comment]
Thank you for the good opinion.

I also agree that support R15 and R16 (before R17).
However, simplicity of having to specify a combination of key-value is lost, if it use dict.
(I think redundant to using "dict:from_list/3")
So, I'm not so keen to be used a dict.

Therefore, I want to adopt an associative array.

Do you have a problem with this?
Do you will be more convenient, if using dict?

**Comment by soranoba** [comment]
If it use an associative array, Implementation looks like this.
https://github.com/soranoba/mustache/commit/af74c264ead4c5dd01037e5ebef5a72c8d0ef6e3

**Comment by tsloughter** [comment]
Yea, that is fine. I did dict for performance, and assumed ppl would just `dict:from_list`. But yours is fine with me. Except you can't have `is_map` at line 112 if this is to support pre-17 releases.

**Comment by soranoba** [comment]
Oops, sorry. Thank you for teaching !

I reflected in the master that this and some tests.
I think it's okay, because I was doing behavior confirmation in R16B03.

https://github.com/soranoba/mustache/compare/v0.1.0...v0.2.0

Now, I close this PR, but I will continue to ask, if there is you opinion on the other.

**Pull request closed without merging**
